// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBitly.Controllers;

namespace MyBitly.Migrations
{
    [DbContext(typeof(UrlContext))]
    [Migration("20190917070219_'UrlData'")]
    partial class UrlData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApplication6.Models.UrlData", b =>
                {
                    b.Property<string>("ShortUrl")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("FullUrl");

                    b.Property<int>("HopCount");

                    b.HasKey("ShortUrl");

                    b.ToTable("UrlDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
